### PR TITLE
Fix `dwave sample` for unstructured solvers

### LINKED ISSUE #557: `dwave sample --random-problem` fails for unstructured solvers
When random problem is generated a structured solver is assumed.

 If user selects an unstructured solver (like BQM/CQM solvers), or such solver gets selected for the user, problem generation will fail:
```
$ dwave sample --random-problem
Unhandled error: AttributeError("'BQMSolver' object has no attribute 'nodes'")
```

### Mitigation
Select a structured solver (QPU) with:
```
$ dwave sample --random-problem --client qpu
```
or
```
$ dwave sample -r -s Advantage_system6.2
```

### Fix
Adapt random problem generation to selected solver (similar to #332).

cc @davage

### PR DESCRIPTION
**Pull request by randomir**
Fix #557.

### CODE REVIEW

**Review by arcondello — APPROVED** [review]
LGTM!

**Comment by davage** [comment]
Looks good. Thanks!

**Review by davage — COMMENTED** [review]
Looks good.

**Review by davage — COMMENTED** [review]
Looks good.

**Review by davage — COMMENTED** [review]
Looks good.

**Pull request merged**
